popug_jira/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks do
    post :assign_all, on: :collection
    patch :complete, on: :member
  end
end

popug_jira/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

popug_jira/app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  before_create :assign_costs!

  scope :incomplete, -> { where(completed: false) }

  def assigned_on?(user)
    assignee_id == user.id
  end

  def assign!(user)
    self.assignee_id = user.id
    save!

    GenerateEvent.call('TaskAssigned', 'tasks-stream',
      cost: assign_cost,
      assignee_id: assignee_id,
      task_name: name,
      task_id: id
    )
  end

  def complete!
    self.completed = true
    save!

    GenerateEvent.call('TaskCompleted', 'tasks-stream',
      cost: complete_cost,
      assignee_id: assignee_id,
      task_name: name,
      task_id: id
    )
  end


  private

  def assign_costs!
    self.assign_cost = rand(-20..-10)
    self.complete_cost = rand(20..40)
  end
end

popug_jira/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :load_auth_info
  helper_method :current_user

  private

  def load_auth_info
    auth_token = cookies[:auth_token]
    return if auth_token.blank?
    @auth_payload, _ = JWT.decode auth_token, nil, false
  end

  def user_authorised?
    @auth_payload.present?
  end

  def user_not_authorised?
    !user_authorised?
  end

  def current_user
    return nil unless user_authorised?
    OpenStruct.new(@auth_payload)
  end

  def chech_signed_in!
    return if user_authorised?
    redirect_to "#{sign_in_url}?redirect_to=#{full_url_for}"
  end

  def sign_in_url
    ENV['AUTH_URL'] + '/sign_in'
  end

  def chech_admin_role!
    return true if current_user.role == 'admin'
    render_403_forbidden
  end

  def render_403_forbidden
    render status: :forbidden, html: 'Forbidden'
  end
end

popug_jira/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :chech_signed_in!
  before_action :chech_admin_role!

  def index
    @tasks = Task.all
    @tasks = @tasks.where(assignee_id: current_user.id) if params[:my]
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task].permit(:name))
    @task.author_id = current_user.id
    if @task.save
      GenerateEvent.call('TaskCreated', 'tasks-stream', **@task.attributes)
      
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def assign_all
    users = GetAllUsers.call
    tasks = Task.incomplete
    
    tasks.each do |task|
      task.assign!(users.sample)
    end

    redirect_to tasks_path
  end

  def complete
    task = Task.find(params[:id])
    task.complete!

    redirect_to tasks_path
  end
end

popug_jira/app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title PopugJira
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

popug_jira/app/views/tasks/_form.html.slim
div
  = simple_form_for @task, wrapper: :inline_form, html: {class: 'form-inline'} do |f|
    = f.input :name, wrapper_html: {class: 'form-group col-md-6' }, input_html: {placeholder: 'Name'}, label: false
    = f.button :submit, class: 'btn btn-primary btn-sm'

popug_jira/app/views/tasks/index.html.slim
= link_to 'All tasks', tasks_path, class: 'btn btn-outline-primary'
'
= link_to 'My tasks', tasks_path(my: true), class: 'btn btn-outline-primary'
'
- if current_user.role.in? %w[manager admin]
  = button_to 'Assign all', assign_all_tasks_path, method: :post, class: 'btn btn-warning', form: { style: 'display:inline-block;' }

table.table
  tr
    th Author
    th Task
    th Assignee
    th Status
    th
  - @tasks.each do |task|
    tr
      td= GetUserInfo.call(task.author_id)&.login
      td= task.name 
      td= GetUserInfo.call(task.assignee_id)&.login
      td= task.completed? ? 'Completed' : 'New'
      td
        - if task.assigned_on?(current_user) && !task.completed?
          '
          = button_to 'Complete', complete_task_path(task), method: :patch, class: 'btn btn-success btn-sm'

= render 'form'

popug_jira/app/views/tasks/new.html.slim
div
  = simple_form_for @task do |f|
    = f.input :name
    = f.button :submit