accounting/config/routes.rb
Rails.application.routes.draw do
  root to: 'accounts#index'

  resources :accounts do
    get :log, on: :member
  end

  get '/my', to: 'accounts#my'
end

accounting/app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  has_many :audit_logs, class_name: 'AccountAuditLog'
end

accounting/app/models/account_audit_log.rb
# frozen_string_literal: true

class AccountAuditLog < ApplicationRecord
  belongs_to :account, inverse_of: :audit_logs

  after_create :update_balance!

  private

  def update_balance!
    account.increment!(:balance, delta)
  end
end

accounting/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

accounting/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :chech_admin_or_accountant_role!

  def index
    today_logs = AccountAuditLog.where('created_at > ?', Date.today)
    @earned_by_management_today = -today_logs.where(kind: %w[TaskCompleted TaskAssigned]).sum(:delta)

    @accounts = Account.all
  end

  def log
    @account = Account.find(params[:id])
    @logs = @account.audit_logs
  end

  def my
    account = Account.find_by(user_id: current_user.id)
    render json: { balance: account.balance }
  end
end

accounting/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :load_auth_info
  helper_method :current_user

  private

  def load_auth_info
    auth_token = cookies[:auth_token]
    return if auth_token.blank?
    @auth_payload, _ = JWT.decode auth_token, nil, false
  end

  def user_authorised?
    @auth_payload.present?
  end

  def user_not_authorised?
    !user_authorised?
  end

  def current_user
    return nil unless user_authorised?
    OpenStruct.new(@auth_payload)
  end

  def chech_signed_in!
    return if user_authorised?
    redirect_to "#{sign_in_url}?redirect_to=#{full_url_for}"
  end

  def sign_in_url
    ENV['AUTH_URL'] + '/sign_in'
  end

  def chech_admin_role!
    return true if current_user.role == 'admin'
    render_403_forbidden
  end

  def chech_admin_or_accountant_role!
    return true if current_user.role.in? %w[admin accountant]
    render_403_forbidden
  end

  def render_403_forbidden
    render status: :forbidden, html: 'Forbidden'
  end
end

accounting/app/helpers/application_helper.rb
module ApplicationHelper
end

accounting/app/views/accounts/index.html.slim
.alert.alert-info Earned by management today: #{@earned_by_management_today}

br

table.table
  tr
    th Author
    th Balance
    th
  - @accounts.each do |account|
    tr
      td= GetUserInfo.call(account.user_id)&.login
      td= account.balance
      td
        = link_to 'log', log_account_path(account), class: 'btn btn-outline-primary btn-sm'

accounting/app/views/accounts/log.slim
table.table
  tr
    th Delta
    th Description
  - @logs.each do |log|
    tr
      td
        code= log.delta
      td= log.description

= link_to 'Back', root_url, class: 'btn'

accounting/app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Accounting
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield